/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Ventana;
import modelo.modelo;
import modelo.usuario;

public class EscritorioPrincipal extends javax.swing.JFrame{
       
    public EscritorioPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        obtenerIdUsuario();
       
        
        //imagen de icono
        
//        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("graficos\\icono.png"));
//        setIconImage(icon);
    }
    
    private void obtenerIdUsuario(){
       usuario user=new usuario();
        txtCategoria.setText(user.getCategoria());
        txtUsuario.setText(user.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        txtCategoria = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        Generar = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        AltaProveedor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuMayoreo = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuVenta1 = new javax.swing.JMenuItem();
        mnuVenta2 = new javax.swing.JMenuItem();
        mnuVenta3 = new javax.swing.JMenuItem();
        mnuVenta4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carniceria Karsad");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        txtCategoria.setText("_");
        desktopPane.add(txtCategoria);
        txtCategoria.setBounds(450, 670, 110, 14);

        jLabel4.setText("Categoria:");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(360, 670, 80, 14);

        jLabel2.setText("Bienvenido:");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(0, 670, 70, 14);

        txtUsuario.setText("_");
        desktopPane.add(txtUsuario);
        txtUsuario.setBounds(80, 670, 240, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/fondo.png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 730);

        txtId.setText("_");
        desktopPane.add(txtId);
        txtId.setBounds(980, 670, 6, 14);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Sistema");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cerrar Sesion");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Salir");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Personal");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Generar");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        Generar.setMnemonic('h');
        Generar.setText("Clientes");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Generar");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        Generar.add(contentMenuItem);

        menuBar.add(Generar);

        AltaProveedor.setText("Proveedores");
        AltaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaProveedorActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Gestión Proveedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        AltaProveedor.add(jMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Gestión de Notas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        AltaProveedor.add(jMenuItem8);

        menuBar.add(AltaProveedor);

        jMenu1.setText("Inventario");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Gestion Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnuMayoreo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuMayoreo.setText("Gestion Mayoreo");
        mnuMayoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMayoreoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuMayoreo);

        menuBar.add(jMenu1);

        mnuVentas.setText("Ventas");

        mnuVenta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuVenta1.setText("Venta 1");
        mnuVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenta1ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenta1);

        mnuVenta2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuVenta2.setText("Venta 2");
        mnuVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenta2ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenta2);

        mnuVenta3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuVenta3.setText("Venta 3");
        mnuVenta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenta3ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenta3);

        mnuVenta4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuVenta4.setText("Venta 4");
        mnuVenta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenta4ActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenta4);

        menuBar.add(mnuVentas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
       altaPersonal alta = new altaPersonal();
       desktopPane.add(alta);
       alta.setLocation(1, 1);
       alta.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       altaProveedor proveedor = new altaProveedor();
        desktopPane.add(proveedor);
        proveedor.setLocation(1, 1);
        proveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        adm_Inventario inventario = new adm_Inventario();
        desktopPane.add(inventario);
        inventario.setLocation(1, 1);
        inventario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        adm_alta_clientes clientes = new adm_alta_clientes();
        desktopPane.add(clientes);
        clientes.setLocation(1, 1);
        clientes.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void AltaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaProveedorActionPerformed
//      // damos de alta proveedor
//        altaProveedor proveedor = new altaProveedor();
//        desktopPane.add(proveedor);
//        proveedor.setLocation(1, 1);
//        proveedor.setVisible(true);
    }//GEN-LAST:event_AltaProveedorActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
             // damos de alta proveedor
        integrarNota nota = new integrarNota();
        desktopPane.add(nota);
        nota.setLocation(30, 30);
        nota.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mnuVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenta1ActionPerformed
            // Iniciamos venta 1
            Venta1 venta1=new Venta1();
        if (Ventana.isVenta1()==false){
            desktopPane.add(venta1);
            venta1.setLocation(30, 30);
            venta1.setVisible(true);
            Ventana.setVenta1(true);
        }else{
            venta1.moveToFront();
            venta1.requestFocus();
            Venta1.txtProducto.requestFocus();
        }     
        
        
    }//GEN-LAST:event_mnuVenta1ActionPerformed

    private void mnuVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenta2ActionPerformed
        Venta2 venta2=new Venta2();
        if (Ventana.isVenta2()==false){
            desktopPane.add(venta2);
            venta2.setLocation(500, 30);
            venta2.setVisible(true);
            Ventana.setVenta2(true);
        }else{
            venta2.moveToFront();
            venta2.requestFocus();
            Venta2.txtProducto.requestFocus();
        }
    }//GEN-LAST:event_mnuVenta2ActionPerformed

    private void mnuVenta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenta3ActionPerformed
         // Iniciamos venta 3
        Venta3 venta3=new Venta3();
         if (Ventana.isVenta3()==false){
            desktopPane.add(venta3);
            venta3.setLocation(30, 250);
            venta3.setVisible(true);
            Ventana.setVenta3(true);
        }else{
            venta3.requestFocus();
            venta3.moveToFront();
            Venta3.txtProducto.requestFocus();}
    }//GEN-LAST:event_mnuVenta3ActionPerformed

    private void mnuVenta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenta4ActionPerformed
        // Iniciamos venta 4
        Venta4 venta4=new Venta4();
        if (Ventana.isVenta4()==false){
            desktopPane.add(venta4);
            venta4.setLocation(500, 250);
            venta4.setVisible(true);
            Ventana.setVenta4(true);
        }else{
            venta4.requestFocus(true);
            venta4.moveToFront();
            Venta4.txtProducto.requestFocus();
        }
    }//GEN-LAST:event_mnuVenta4ActionPerformed

    private void mnuMayoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMayoreoActionPerformed
        adm_Mayoreo mayoreo = new adm_Mayoreo();
        desktopPane.add(mayoreo);
        mayoreo.setLocation(1, 1);
        mayoreo.setVisible(true);
    }//GEN-LAST:event_mnuMayoreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscritorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscritorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscritorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscritorioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscritorioPrincipal().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AltaProveedor;
    private javax.swing.JMenu Generar;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuMayoreo;
    private javax.swing.JMenuItem mnuVenta1;
    private javax.swing.JMenuItem mnuVenta2;
    private javax.swing.JMenuItem mnuVenta3;
    private javax.swing.JMenuItem mnuVenta4;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel txtCategoria;
    public static javax.swing.JLabel txtId;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

}
